export const projects = [
    {
      href: '/apps/realtor-simplified',
      name: 'Realtor Simplified',
      full: true,
      description: ' saas platform that enables realtors to deploy a professional website in minutes.',
      image: { src: '/me.jpeg' },
    },
    {
      href: '/apps/loteria-monarca',
      name: 'Loteria Monarca',
      full: true,
      description: ' online platform to register and play Loteria Mexicana.',
      image: { src: '/me.jpeg' },
    },
    {
      href: '/apps/realtor-template-1',
      name: 'Realtor Template',
      full: false,
      description: ' deployable template on the realtor simplified platform.',
      image: { src: '/me.jpeg' },
    },
    {
      href: '/apps/sierra-ecomaderas',
      name: 'Sierra Ecomanderas',
      full: false,
      description: ' static website for a wood selling bussiness.',
      image: { src: '/me.jpeg' },
    },
    {
      href: '/apps/leenith-borges',
      name: 'Leenith',
      full: true,
      description: ' e-commerce website to manage, and sell courses online.',
      image: { src: '/me.jpeg' },
    },
    {
      href: '/apps/leenith-borges',
      name: 'Leenith IOS',
      full: false,
      description: ' ios app to access and buy courses.',
      image: { src: '/me.jpeg' },
    },
    {
      href: '/apps/impulseux',
      name: 'ImpulseUX',
      full: false,
      description: ' static website for design and development agency.',
      image: { src: '/me.jpeg' },
    },
  ];